version: '3.8'

services:
  go-matrix-api:
    build:
      context: ./go-matrix-api
      dockerfile: Dockerfile
    container_name: go-matrix-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=super_secret_jwt_key_interseguro
      - NODE_API_URL=http://node-analytics-api:4000/api/analytics # Cambiará cuando agreguemos Node
    restart: unless-stopped
    networks:
      - interseguro-net

  node-analytics-api:
    build:
      context: ./node-analytics-api
      dockerfile: Dockerfile
    container_name: node-analytics-api
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET=super_secret_jwt_key_interseguro
    restart: unless-stopped
    networks:
      - interseguro-net

networks:
  interseguro-net:
    driver: bridge
